# Generated by Django 5.2.6 on 2025-09-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_category_alter_job_city_alter_job_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effoysira_last_job_link', models.URLField(blank=True, null=True)),
                ('ethiojobs_last_job_link', models.URLField(blank=True, null=True)),
                ('hamerejobs_last_job_link', models.URLField(blank=True, null=True)),
                ('kebenajobs_last_job_link', models.URLField(blank=True, null=True)),
                ('hiring_cafe_last_job_id', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
