# Generated by Django 5.2.6 on 2025-09-22 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_scraperstate'),
        ('user', '0004_recruiterprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.recruiterprofile'),
        ),
    ]
